# Generated by Django 5.0.3 on 2024-03-07 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 17, 47, 2, 334625)),
        ),
    ]
